PATH = 'module/assets/'

# Texture settings
SIZEX = 10000
SIZEY = 10000
SCALE = 10
CYLINDER_TEXTURE = PATH + 'sin_stripes.png'
DPI = 500

# Experiment settings
CYLINDER_POSITION = 0, 0, -2
CYLINDER_SPEEDS = 9., 14.
CYLINDER_ROTATION_X = 90

PHASE_DURATION_SECS = 5.
WAIT_DURATION_SECS = 1
START_TIME = 1

SEQ = None
