# Texture settings
SIZE = 10000
SCALE = 50
CYLINDER_TEXTURE = 'scripts/assets/sin_stripes.png'
DPI = 500

# Experiment settings
CYLINDER_POSITION = 0, 0, -2
CYLINDER_SPEEDS = 9., 14.
CYLINDER_ROTATION_X = 90

PHASE_DURATION_SECS = 5.
WAIT_DURATION_SECS = 2
START_TIME = 2
